// Universal European Country Code, Name & Tricode Mapping
export const COUNTRY_NAMES: Record<string, string> = {
  'gb-eng': 'England',
  'gb-sct': 'Scotland',
  'gb-wls': 'Wales',
  'gb-nir': 'Northern Ireland',
  'gb': 'England',
  'uk': 'England',
  'ie': 'Republic of Ireland',
  'de': 'Germany',
  'fr': 'France',
  'es': 'Spain',
  'it': 'Italy',
  'nl': 'Netherlands',
  'pt': 'Portugal',
  'be': 'Belgium',
  'hr': 'Croatia',
  'dk': 'Denmark',
  'se': 'Sweden',
  'ch': 'Switzerland',
  'at': 'Austria',
  'pl': 'Poland',
  'cz': 'Czechia',
  'cs': 'Czechoslovakia',
  'tr': 'Türkiye',
  'gr': 'Greece',
  'hu': 'Hungary',
  'ua': 'Ukraine',
  'ro': 'Romania',
  'rs': 'Serbia',
  'yu': 'Yugoslavia',
  'su': 'Soviet Union',
  'cis': 'CIS',
  'no': 'Norway',
  'sk': 'Slovakia',
  'si': 'Slovenia',
  'fi': 'Finland',
  'al': 'Albania',
  'ge': 'Georgia',
  'is': 'Iceland',
  'bg': 'Bulgaria',
  'ba': 'Bosnia & Herzegovina',
  'mk': 'North Macedonia',
  'me': 'Montenegro',
  'cy': 'Cyprus',
  'il': 'Israel',
  'lu': 'Luxembourg',
  'am': 'Armenia',
  'az': 'Azerbaijan',
  'kz': 'Kazakhstan',
  'xk': 'Kosovo',
  'ee': 'Estonia',
  'lv': 'Latvia',
  'lt': 'Lithuania',
  'md': 'Moldova',
  'by': 'Belarus',
  'mt': 'Malta',
  'fo': 'Faroe Islands',
  'ad': 'Andorra',
  'sm': 'San Marino',
  'li': 'Liechtenstein',
  'gi': 'Gibraltar',
  'eu': 'Europe (All-Stars)'
}

export const COUNTRY_TRICODES: Record<string, string> = {
  'gb-eng': 'ENG',
  'gb-sct': 'SCO',
  'gb-wls': 'WAL',
  'gb-nir': 'NIR',
  'gb': 'ENG',
  'uk': 'ENG',
  'ie': 'IRL',
  'de': 'GER',
  'fr': 'FRA',
  'es': 'ESP',
  'it': 'ITA',
  'nl': 'NED',
  'pt': 'POR',
  'be': 'BEL',
  'hr': 'CRO',
  'dk': 'DEN',
  'se': 'SWE',
  'ch': 'SUI',
  'at': 'AUT',
  'pl': 'POL',
  'cz': 'CZE',
  'cs': 'TCH',
  'tr': 'TUR',
  'gr': 'GRE',
  'hu': 'HUN',
  'ua': 'UKR',
  'ro': 'ROU',
  'rs': 'SRB',
  'yu': 'YUG',
  'su': 'URS',
  'cis': 'CIS',
  'no': 'NOR',
  'sk': 'SVK',
  'si': 'SVN',
  'fi': 'FIN',
  'al': 'ALB',
  'ge': 'GEO',
  'is': 'ISL',
  'bg': 'BUL',
  'ba': 'BIH',
  'mk': 'MKD',
  'me': 'MNE',
  'cy': 'CYP',
  'il': 'ISR',
  'lu': 'LUX',
  'am': 'ARM',
  'az': 'AZE',
  'kz': 'KAZ',
  'xk': 'KOS',
  'ee': 'EST',
  'lv': 'LAT',
  'lt': 'LTU',
  'md': 'MDA',
  'by': 'BLR',
  'mt': 'MLT',
  'fo': 'FRO',
  'ad': 'AND',
  'sm': 'SMR',
  'li': 'LIE',
  'gi': 'GIB',
  'eu': 'EUR'
}

export function getCountryName(code: string): string {
  if (!code) return ''
  const clean = code.toLowerCase().trim()
  return COUNTRY_NAMES[clean] || (clean === 'gb' ? 'England' : clean.toUpperCase())
}

export function getCountryTriCode(code: string): string {
  if (!code) return ''
  const clean = code.toLowerCase().trim()
  return COUNTRY_TRICODES[clean] || (clean === 'gb' ? 'ENG' : clean.length === 2 ? clean.toUpperCase() : clean.slice(-3).toUpperCase())
}
