import type { PositionCode } from '../app/types'

export interface PlayerPositionProfile {
  primary: PositionCode
  positions: PositionCode[]
  base: 'Goalkeeper' | 'Defender' | 'Midfielder' | 'Forward'
  baseRating?: number
}

// Comprehensive registry of verified historical player positions for Euro stars & legends
export const HISTORICAL_PLAYER_REGISTRY: Record<string, PlayerPositionProfile> = {
  // Additional Italian & French Legends & Dutch 1988 Champions
  'david trezeguet': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 89 },
  'nicolas anelka': { primary: 'ST', positions: ['ST', 'CF', 'RW'], base: 'Forward', baseRating: 88 },
  'emmanuel petit': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 87 },
  'youri djorkaeff': { primary: 'CAM', positions: ['CAM', 'ST', 'CF'], base: 'Midfielder', baseRating: 88 },
  'christophe dugarry': { primary: 'ST', positions: ['ST', 'LW', 'CF'], base: 'Forward', baseRating: 84 },
  'frank leboeuf': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'frank leboeuf': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'jocelyn angloma': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender', baseRating: 84 },
  'christian karembeu': { primary: 'CDM', positions: ['CDM', 'CM', 'RB'], base: 'Midfielder', baseRating: 85 },
  'johan micoud': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 85 },
  'alessandro del piero': { primary: 'ST', positions: ['ST', 'CF', 'LW', 'CAM'], base: 'Forward', baseRating: 92 },
  'gianfranco zola': { primary: 'CAM', positions: ['CAM', 'CF', 'ST'], base: 'Forward', baseRating: 90 },
  'roberto mancini': { primary: 'CAM', positions: ['CAM', 'CF'], base: 'Forward', baseRating: 89 },
  'claudio marchisio': { primary: 'CM', positions: ['CM', 'CDM', 'CAM'], base: 'Midfielder', baseRating: 87 },
  'leonardo spinazzola': { primary: 'LB', positions: ['LB', 'LM'], base: 'Defender', baseRating: 86 },
  'manuel locatelli': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 85 },
  'domenico berardi': { primary: 'RW', positions: ['RW', 'RM'], base: 'Forward', baseRating: 86 },
  'hans van breukelen': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 88 },
  'jan wouters': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 87 },
  'gerald vanenburg': { primary: 'RW', positions: ['RW', 'RM'], base: 'Midfielder', baseRating: 87 },
  'arnold muhren': { primary: 'LM', positions: ['LM', 'CM'], base: 'Midfielder', baseRating: 87 },
  'erwin koeman': { primary: 'LM', positions: ['LM', 'LB'], base: 'Midfielder', baseRating: 86 },

  // ==================== GOALKEEPERS ====================
  'iker casillas': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 92 },
  'gianluigi buffon': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 93 },
  'manuel neuer': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 93 },
  'petr cech': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 91 },
  'peter schmeichel': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 91 },
  'edwin van der sar': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 90 },
  'fabien barthez': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 89 },
  'hugo lloris': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 88 },
  'oliver kahn': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 91 },
  'jens lehmann': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'sepp maier': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 90 },
  'dino zoff': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 92 },
  'lev yashin': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 93 },
  'ivo viktor': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'david seaman': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 88 },
  'jordan pickford': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'thibaut courtois': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 90 },
  'gianluigi donnarumma': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 89 },
  'rui patricio': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'vitor baia': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'andreas isaksson': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 84 },
  'igor akinfeev': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 86 },
  'volkan demirel': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 85 },
  'rustu recber': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'steve mandanda': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper' },
  'pepe reina': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper' },
  'david de gea': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 89 },
  'unai simon': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'dominik livakovic': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 86 },
  'kasper schmeichel': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'wojciech szczesny': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },
  'lukasz fabianski': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper' },
  'andriy pyatov': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper' },
  'yann sommer': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },

  // ==================== DEFENDERS: CENTRE-BACKS ====================
  'franz beckenbauer': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 94 },
  'sergio ramos': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 92 },
  'carles puyol': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 91 },
  'virgil van dijk': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 91 },
  'pepe': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 89 },
  'giorgio chiellini': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender', baseRating: 90 },
  'leonardo bonucci': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 89 },
  'john terry': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 90 },
  'rio ferdinand': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 90 },
  'fabio cannavaro': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 91 },
  'alessandro nesta': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 92 },
  'franco baresi': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 93 },
  'marcel desailly': { primary: 'CB', positions: ['CB', 'CDM'], base: 'Defender', baseRating: 91 },
  'laurent blanc': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 90 },
  'ronald koeman': { primary: 'CB', positions: ['CB', 'CDM'], base: 'Defender', baseRating: 91 },
  'jaap stam': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 90 },
  'frank de boer': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender' },
  'gerard pique': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 90 },
  'mats hummels': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 89 },
  'jerome boateng': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 88 },
  'per mertesacker': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 86 },
  'raphael varane': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 89 },
  'ruben dias': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 89 },
  'antonio rudiger': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 88 },
  'aymeric laporte': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 88 },
  'ricardo carvalho': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 89 },
  'bruno alves': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'jose fonte': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'sol campbell': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 89 },
  'tony adams': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'gary cahill': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'john stones': { primary: 'CB', positions: ['CB', 'CDM'], base: 'Defender', baseRating: 88 },
  'harry maguire': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'marc guehi': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'matthias sammer': { primary: 'CB', positions: ['CB', 'CDM'], base: 'Defender', baseRating: 91 },
  'jurgen kohler': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 89 },
  'alessandro costacurta': { primary: 'CB', positions: ['CB', 'LB', 'RB'], base: 'Defender', baseRating: 89 },
  'giuseppe bergomi': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 89 },
  'sandor matrai': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'tomas sivok': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'roman hubnik': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'michal kadlec': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender' },
  'marek suchy': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'jan vertonghen': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender' },
  'toby alderweireld': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender' },
  'thomas vermaelen': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender' },
  'vincent kompany': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 90 },
  'manuel akanji': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 88 },
  'fabian schar': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'robin le normand': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'nacho': { primary: 'CB', positions: ['CB', 'RB', 'LB'], base: 'Defender', baseRating: 85 },
  'raul albiol': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 85 },
  'carlos marchena': { primary: 'CB', positions: ['CB', 'CDM'], base: 'Defender', baseRating: 86 },
  'sergei ignashevich': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 86 },
  'vasili berezutski': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender' },
  'aleksei berezutski': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender' },
  'simon kjaer': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 86 },
  'daniel agger': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 86 },
  'andreas christensen': { primary: 'CB', positions: ['CB', 'CDM'], base: 'Defender', baseRating: 86 },
  'joachim andersen': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'olof mellberg': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 86 },
  'patrik andersson': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 87 },
  'victor lindelof': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'andreas granqvist': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'domagoj vida': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender', baseRating: 85 },
  'dejan lovren': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'josko gvardiol': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender', baseRating: 88 },
  'robert kovac': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'dario simic': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender' },
  'kamil glik': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 86 },
  'michal pazdan': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'jan bednarek': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'servet cetin': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 85 },
  'merih demiral': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 86 },
  'caglar soyuncu': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'abdulkerim bardakci': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'kaan ayhan': { primary: 'CB', positions: ['CB', 'CDM', 'RB'], base: 'Defender' },
  'samet akaydin': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'martin skrtel': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 86 },
  'jan durica': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'milan skriniar': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 88 },
  'denis vavro': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'mykola matviyenko': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender' },
  'illia zabarnyi': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'oleksandr kucher': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'taras mykhalyk': { primary: 'CB', positions: ['CB', 'CDM'], base: 'Defender' },
  'yevhen khacheridi': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'nikola milenkovic': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender' },
  'strahinja pavlovic': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'milos veljkovic': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'sinisa mihajlovic': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender', baseRating: 89 },
  'miroslav djoukic': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'mladen krstajic': { primary: 'CB', positions: ['CB', 'LB'], base: 'Defender' },
  'nemanja vidic': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 90 },
  'traianos dellas': { primary: 'CB', positions: ['CB'], base: 'Defender', baseRating: 87 },
  'michalis kapsis': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'sokratis papastathopoulos': { primary: 'CB', positions: ['CB', 'RB'], base: 'Defender' },
  'kostas manolas': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'avraam papadopoulos': { primary: 'CB', positions: ['CB'], base: 'Defender' },
  'kyriakos papadopoulos': { primary: 'CB', positions: ['CB', 'CDM'], base: 'Defender' },

  // ==================== DEFENDERS: LEFT-BACKS ====================
  'paolo maldini': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender', baseRating: 94 },
  'roberto carlos': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 92 },
  'ashley cole': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 90 },
  'jordi alba': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 89 },
  'patrice evra': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 88 },
  'bixente lizarazu': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 89 },
  'andreas brehme': { primary: 'LB', positions: ['LB', 'RB'], base: 'Defender', baseRating: 90 },
  'fabio grosso': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 87 },
  'joan capdevila': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 86 },
  'david alaba': { primary: 'LB', positions: ['LB', 'CB', 'CM'], base: 'Defender', baseRating: 89 },
  'luke shaw': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender', baseRating: 86 },
  'nuno mendes': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 87 },
  'theo hernandez': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 88 },
  'lucas hernandez': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender', baseRating: 87 },
  'ferland mendy': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 86 },
  'lucas digne': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 85 },
  'eric abidal': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender', baseRating: 87 },
  'giovanni van bronckhorst': { primary: 'LB', positions: ['LB', 'CM'], base: 'Defender', baseRating: 87 },
  'robert jarni': { primary: 'LB', positions: ['LB', 'LM'], base: 'Defender', baseRating: 87 },
  'fabio coentrao': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 87 },
  'raphael guerreiro': { primary: 'LB', positions: ['LB', 'CM'], base: 'Defender', baseRating: 86 },
  'david limbersky': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'yuri zhirkov': { primary: 'LB', positions: ['LB', 'LM'], base: 'Defender', baseRating: 87 },
  'marc cucurella': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 86 },
  'andy robertson': { primary: 'LB', positions: ['LB'], base: 'Defender', baseRating: 88 },
  'kieran tierney': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender', baseRating: 85 },
  'leighton baines': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'christian ziege': { primary: 'LB', positions: ['LB', 'LM'], base: 'Defender', baseRating: 86 },
  'michael tarnat': { primary: 'LB', positions: ['LB', 'LM'], base: 'Defender' },
  'jonas hector': { primary: 'LB', positions: ['LB', 'CDM'], base: 'Defender' },
  'marcel halstenberg': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender' },
  'david raum': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'maximilian mittelstadt': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'ricardo rodriguez': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender', baseRating: 86 },
  'ivan strinic': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'borna sosa': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'danijel pranjic': { primary: 'LB', positions: ['LB', 'LM'], base: 'Defender' },
  'hakan balta': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender' },
  'caner erkin': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'ferdi kadioglu': { primary: 'LB', positions: ['LB', 'RB'], base: 'Defender', baseRating: 86 },
  'jakub wawrzyniak': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'artur jedrzejczyk': { primary: 'LB', positions: ['LB', 'RB', 'CB'], base: 'Defender' },
  'tymoteusz puchacz': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'vitaliy mykolenko': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'takis fyssas': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'jose holebas': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'georgios tzavellas': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender' },
  'mikael lustig': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender' },
  'martin olsson': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'ludwig augustinsson': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'tomas hubocan': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender' },
  'peter pekarik': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'david hancko': { primary: 'LB', positions: ['LB', 'CB'], base: 'Defender', baseRating: 85 },

  // ==================== DEFENDERS: RIGHT-BACKS ====================
  'philipp lahm': { primary: 'RB', positions: ['RB', 'LB', 'CDM'], base: 'Defender', baseRating: 92 },
  'dani carvajal': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 89 },
  'gary neville': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 88 },
  'kyle walker': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender', baseRating: 88 },
  'lilian thuram': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender', baseRating: 90 },
  'gianluca zambrotta': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender', baseRating: 89 },
  'stephan lichtsteiner': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 86 },
  'bacary sagna': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 86 },
  'joshua kimmich': { primary: 'RB', positions: ['RB', 'CDM', 'CM'], base: 'Defender', baseRating: 89 },
  'darijo srna': { primary: 'RB', positions: ['RB', 'RM'], base: 'Defender', baseRating: 88 },
  'thomas meunier': { primary: 'RB', positions: ['RB', 'RM'], base: 'Defender', baseRating: 85 },
  'kieran trippier': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender', baseRating: 86 },
  'trent alexander-arnold': { primary: 'RB', positions: ['RB', 'CM'], base: 'Defender', baseRating: 88 },
  'denzel dumfries': { primary: 'RB', positions: ['RB', 'RM'], base: 'Defender', baseRating: 86 },
  'michel salgado': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 87 },
  'alvaro arbeloa': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender', baseRating: 85 },
  'juanfran': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 85 },
  'willy sagnol': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 87 },
  'christian panucci': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender', baseRating: 87 },
  'theodor gebre selassie': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'frantisek rajtoral': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'vladimir coufal': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'cedric soares': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'joao cancelo': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender', baseRating: 88 },
  'diogo dalot': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender', baseRating: 86 },
  'nelson semedo': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'miguel': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'paulo ferreira': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender' },
  'benjamin pavard': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender', baseRating: 86 },
  'jules kounde': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender', baseRating: 87 },
  'lukasz piszczek': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 87 },
  'josip juranovic': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender' },
  'sime vrsaljko': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 85 },
  'vedran corluka': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender' },
  'gokhan gonul': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 85 },
  'sener ozbayrakli': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'zeki celik': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'mert muldur': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender' },
  'oleksandr karavayev': { primary: 'RB', positions: ['RB', 'RM'], base: 'Defender' },
  'bohdan mykhaylichenko': { primary: 'LB', positions: ['LB'], base: 'Defender' },
  'giourkas seitaridis': { primary: 'RB', positions: ['RB'], base: 'Defender', baseRating: 87 },
  'vasilis torosidis': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender' },
  'loukas vyntra': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender' },
  'arne friedrich': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender' },
  'lukas klostermann': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender' },
  'gregory van der wiel': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'michael reiziger': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'mario melchiot': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender' },
  'timothy castagne': { primary: 'RB', positions: ['RB', 'LB'], base: 'Defender' },
  'silvan widmer': { primary: 'RB', positions: ['RB'], base: 'Defender' },
  'michael lang': { primary: 'RB', positions: ['RB', 'CB'], base: 'Defender' },

  // ==================== MIDFIELDERS: DEFENSIVE MIDFIELDERS ====================
  'sergio busquets': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 91 },
  'claude makelele': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 90 },
  'n\'golo kante': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder' },
  'ngolo kante': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 90 },
  'roy keane': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 90 },
  'patrick vieira': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 92 },
  'gennaro gattuso': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 88 },
  'casemiro': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 90 },
  'rodri': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 92 },
  'didier deschamps': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 89 },
  'xabi alonso': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 90 },
  'declan rice': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 89 },
  'daniele de rossi': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 89 },
  'andrea pirlo': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 92 },
  'marco verratti': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 89 },
  'bastian schweinsteiger': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 90 },
  'sami khedira': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 87 },
  'axel witsel': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 87 },
  'marcelo brozovic': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 88 },
  'marouane fellaini': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 85 },
  'tomas hubschman': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder' },
  'jeremy toulalan': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder' },
  'alou diarra': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder' },
  'marcos senna': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 88 },
  'david albelda': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder' },
  'costinha': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 86 },
  'maniche': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'william carvalho': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 86 },
  'joao palhinha': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 87 },
  'danilo pereira': { primary: 'CDM', positions: ['CDM', 'CB'], base: 'Midfielder', baseRating: 86 },
  'nigel de jong': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 86 },
  'mark van bommel': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 87 },
  'mehmet aurelio': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder' },
  'ismail yuksek': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder' },
  'salih ozcan': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder' },
  'okay yokuslu': { primary: 'CDM', positions: ['CDM', 'CB'], base: 'Midfielder' },
  'grzegorz krychowiak': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 86 },
  'taras stepanenko': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder', baseRating: 85 },
  'anatoliy tymoshchuk': { primary: 'CDM', positions: ['CDM', 'CB'], base: 'Midfielder', baseRating: 87 },
  'igor denisov': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder' },
  'jens jeremies': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder' },
  'dietmar hamann': { primary: 'CDM', positions: ['CDM'], base: 'Midfielder' },
  'carsten ramelow': { primary: 'CDM', positions: ['CDM', 'CB'], base: 'Midfielder' },
  'angelos basinas': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder' },
  'kostas katsouranis': { primary: 'CDM', positions: ['CDM', 'CM', 'CB'], base: 'Midfielder' },
  'theodoros zagorakis': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 88 },
  'emre belozoglu': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder' },
  'tomas soucek': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 86 },
  'alex kral': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder' },
  'juraj kucka': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'patrik hrosovsky': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'stanislav lobotka': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 87 },

  // ==================== MIDFIELDERS: CENTRAL MIDFIELDERS ====================
  'toni kroos': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 92 },
  'luka modric': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 93 },
  'xavi': { primary: 'CM', positions: ['CM'], base: 'Midfielder', baseRating: 93 },
  'andres iniesta': { primary: 'CM', positions: ['CM', 'CAM', 'LW'], base: 'Midfielder', baseRating: 94 },
  'paul scholes': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 91 },
  'steven gerrard': { primary: 'CM', positions: ['CM', 'CAM', 'RM'], base: 'Midfielder', baseRating: 91 },
  'frank lampard': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 91 },
  'clarence seedorf': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 91 },
  'michael ballack': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 91 },
  'lothar matthaus': { primary: 'CM', positions: ['CM', 'CB', 'CDM'], base: 'Midfielder', baseRating: 93 },
  'paul pogba': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 89 },
  'ilkay gundogan': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 89 },
  'frenkie de jong': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 89 },
  'cesc fabregas': { primary: 'CM', positions: ['CM', 'CAM', 'CF'], base: 'Midfielder', baseRating: 89 },
  'deco': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 90 },
  'ruud gullit': { primary: 'CM', positions: ['CM', 'CAM', 'ST'], base: 'Midfielder', baseRating: 93 },
  'frank rijkaard': { primary: 'CDM', positions: ['CDM', 'CB'], base: 'Midfielder', baseRating: 92 },
  'aron winter': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'kim kallstrom': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder' },
  'jaroslav plasil': { primary: 'CM', positions: ['CM', 'LM'], base: 'Midfielder' },
  'petr jiracek': { primary: 'CM', positions: ['CM', 'LM'], base: 'Midfielder' },
  'vladimir darida': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder' },
  'daniel kolar': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder' },
  'mateo kovacic': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 88 },
  'ivan rakitic': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 89 },
  'marcel sabitzer': { primary: 'CM', positions: ['CM', 'CAM', 'RM'], base: 'Midfielder', baseRating: 87 },
  'konrad laimer': { primary: 'CM', positions: ['CM', 'RB', 'CDM'], base: 'Midfielder' },
  'granit xhaka': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 88 },
  'remo freuler': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'adrien rabiot': { primary: 'CM', positions: ['CM', 'LM'], base: 'Midfielder', baseRating: 87 },
  'blaise matuidi': { primary: 'CM', positions: ['CM', 'LM'], base: 'Midfielder', baseRating: 87 },
  'yohan cabaye': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'moussa sissoko': { primary: 'CM', positions: ['CM', 'RM'], base: 'Midfielder' },
  'morgan schneiderlin': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder' },
  'corentin tolisso': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'jordan henderson': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'jude bellingham': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 91 },
  'kobbie mainoo': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'joao moutinho': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 88 },
  'ruben neves': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder', baseRating: 87 },
  'vitinha': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder', baseRating: 87 },
  'tiago': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'raul meireles': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'renato sanches': { primary: 'CM', positions: ['CM', 'RM'], base: 'Midfielder', baseRating: 86 },
  'oguzhan ozyakup': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder' },
  'ozan tufan': { primary: 'CM', positions: ['CM', 'RB'], base: 'Midfielder' },
  'hakan calhanoglu': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 88 },
  'piotr zielinski': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 87 },
  'karol linetty': { primary: 'CM', positions: ['CM'], base: 'Midfielder' },
  'mateusz klich': { primary: 'CM', positions: ['CM'], base: 'Midfielder' },
  'oleksandr zinchenko': { primary: 'CM', positions: ['CM', 'LB', 'LM'], base: 'Midfielder', baseRating: 86 },
  'ruslan malinovskyi': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder' },
  'mykola shaparenko': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder' },
  'sergej milinkovic-savic': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 88 },
  'sasa lukic': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'nemanja maksimovic': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'dragan stojkovic': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder' },
  'vladimir jugovic': { primary: 'CM', positions: ['CM', 'LM'], base: 'Midfielder' },
  'albert sambi lokonga': { primary: 'CM', positions: ['CM', 'CDM'], base: 'Midfielder' },
  'youri tielemans': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder', baseRating: 87 },
  'leander dendoncker': { primary: 'CDM', positions: ['CDM', 'CB'], base: 'Midfielder' },
  'amadou onana': { primary: 'CDM', positions: ['CDM', 'CM'], base: 'Midfielder' },
  'orestis karnezis': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper' },
  'antonis nikopolidis': { primary: 'GK', positions: ['GK'], base: 'Goalkeeper', baseRating: 87 },

  // ==================== MIDFIELDERS: ATTACKING MIDFIELDERS / PLAYMAKERS ====================
  'zinedine zidane': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 94 },
  'mesut ozil': { primary: 'CAM', positions: ['CAM', 'LW', 'RW'], base: 'Midfielder', baseRating: 90 },
  'tomas rosicky': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 89 },
  'kevin de bruyne': { primary: 'CAM', positions: ['CAM', 'CM', 'RW'], base: 'Midfielder', baseRating: 93 },
  'wesley sneijder': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 92 },
  'rui costa': { primary: 'CAM', positions: ['CAM'], base: 'Midfielder', baseRating: 91 },
  'michael laudrup': { primary: 'CAM', positions: ['CAM', 'LW', 'RW'], base: 'Midfielder', baseRating: 92 },
  'gheorghe hagi': { primary: 'CAM', positions: ['CAM', 'LW'], base: 'Midfielder', baseRating: 91 },
  'michel platini': { primary: 'CAM', positions: ['CAM', 'CF'], base: 'Midfielder', baseRating: 94 },
  'roberto baggio': { primary: 'CAM', positions: ['CAM', 'ST', 'CF'], base: 'Midfielder', baseRating: 93 },
  'francesco totti': { primary: 'CAM', positions: ['CAM', 'CF', 'ST'], base: 'Midfielder', baseRating: 92 },
  'christian eriksen': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 89 },
  'bruno fernandes': { primary: 'CAM', positions: ['CAM', 'CM', 'RW'], base: 'Midfielder', baseRating: 89 },
  'jamal musiala': { primary: 'CAM', positions: ['CAM', 'LW', 'RW'], base: 'Midfielder', baseRating: 90 },
  'florian wirtz': { primary: 'CAM', positions: ['CAM', 'LW'], base: 'Midfielder', baseRating: 89 },
  'thomas muller': { primary: 'CAM', positions: ['CAM', 'CF', 'RW', 'ST'], base: 'Forward', baseRating: 90 },
  'isco': { primary: 'CAM', positions: ['CAM', 'LW', 'CM'], base: 'Midfielder', baseRating: 88 },
  'mario gotze': { primary: 'CAM', positions: ['CAM', 'LW', 'CF'], base: 'Midfielder', baseRating: 88 },
  'marek hamsik': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 88 },
  'pavel nedved': { primary: 'CAM', positions: ['CAM', 'LM', 'LW'], base: 'Midfielder', baseRating: 92 },
  'robert pires': { primary: 'LM', positions: ['LM', 'LW', 'CAM'], base: 'Midfielder', baseRating: 89 },
  'david silva': { primary: 'CAM', positions: ['CAM', 'LW', 'RW', 'CM'], base: 'Midfielder', baseRating: 90 },
  'santi cazorla': { primary: 'CAM', positions: ['CAM', 'CM', 'LW'], base: 'Midfielder', baseRating: 88 },
  'juan mata': { primary: 'CAM', positions: ['CAM', 'RW', 'LW'], base: 'Midfielder', baseRating: 88 },
  'thiago alcantara': { primary: 'CM', positions: ['CM', 'CAM', 'CDM'], base: 'Midfielder', baseRating: 89 },
  'thiago': { primary: 'CM', positions: ['CM', 'CAM', 'CDM'], base: 'Midfielder' },
  'dimitri payet': { primary: 'CAM', positions: ['CAM', 'LW'], base: 'Midfielder', baseRating: 87 },
  'mathieu valbuena': { primary: 'CAM', positions: ['CAM', 'RW'], base: 'Midfielder' },
  'samir nasri': { primary: 'CAM', positions: ['CAM', 'LW', 'RW'], base: 'Midfielder', baseRating: 87 },
  'yoann gourcuff': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder' },
  'mario pasalic': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder' },
  'lovro majer': { primary: 'CAM', positions: ['CAM', 'RW', 'CM'], base: 'Midfielder' },
  'nikola vlasic': { primary: 'CAM', positions: ['CAM', 'RW', 'LW'], base: 'Midfielder' },
  'xherdan shaqiri': { primary: 'CAM', positions: ['CAM', 'RW'], base: 'Midfielder', baseRating: 87 },
  'christoph baumgartner': { primary: 'CAM', positions: ['CAM', 'LW', 'ST'], base: 'Midfielder' },
  'arda turan': { primary: 'CAM', positions: ['CAM', 'LW', 'LM'], base: 'Midfielder', baseRating: 88 },
  'yusuf yazici': { primary: 'CAM', positions: ['CAM', 'CF'], base: 'Midfielder' },
  'arda guler': { primary: 'CAM', positions: ['CAM', 'RW'], base: 'Midfielder', baseRating: 87 },
  'alan dzagoev': { primary: 'CAM', positions: ['CAM', 'LW', 'RW'], base: 'Midfielder', baseRating: 86 },
  'andrey arshavin': { primary: 'CAM', positions: ['CAM', 'LW', 'ST'], base: 'Forward', baseRating: 88 },
  'konstantin zyryanov': { primary: 'CM', positions: ['CM', 'CAM'], base: 'Midfielder' },
  'roman shirokov': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder' },
  'emil forsberg': { primary: 'CAM', positions: ['CAM', 'LW'], base: 'Midfielder', baseRating: 87 },
  'antonin panenka': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder', baseRating: 88 },
  'karel poborsky': { primary: 'RM', positions: ['RM', 'RW'], base: 'Midfielder', baseRating: 88 },
  'vladimir smicer': { primary: 'CAM', positions: ['CAM', 'LW', 'ST'], base: 'Midfielder', baseRating: 87 },
  'patrik berger': { primary: 'CAM', positions: ['CAM', 'LM'], base: 'Midfielder', baseRating: 87 },
  'milan petrzela': { primary: 'RM', positions: ['RM', 'RW'], base: 'Midfielder' },
  'vaclav pilar': { primary: 'LW', positions: ['LW', 'LM'], base: 'Forward' },
  'ondrej duda': { primary: 'CAM', positions: ['CAM', 'CM'], base: 'Midfielder' },
  'lukas haraslin': { primary: 'LW', positions: ['LW', 'LM'], base: 'Forward' },

  // ==================== MIDFIELDERS: WIDE MIDFIELDERS ====================
  'david beckham': { primary: 'RM', positions: ['RM', 'RW', 'CM'], base: 'Midfielder', baseRating: 90 },
  'freddie ljungberg': { primary: 'RM', positions: ['RM', 'RW', 'CAM'], base: 'Midfielder', baseRating: 88 },
  'marc overmars': { primary: 'LM', positions: ['LM', 'LW', 'RW'], base: 'Midfielder', baseRating: 89 },
  'ryan giggs': { primary: 'LM', positions: ['LM', 'LW'], base: 'Midfielder', baseRating: 90 },
  'jesus navas': { primary: 'RW', positions: ['RW', 'RM', 'RB'], base: 'Forward', baseRating: 87 },
  'joaquin': { primary: 'RW', positions: ['RW', 'RM'], base: 'Midfielder' },
  'vicente': { primary: 'LM', positions: ['LM', 'LW'], base: 'Midfielder' },
  'boudewijn zenden': { primary: 'LM', positions: ['LM', 'LW', 'LB'], base: 'Midfielder' },
  'alessandro florenzi': { primary: 'RB', positions: ['RB', 'RM', 'CM'], base: 'Defender' },
  'antonio candreva': { primary: 'RM', positions: ['RM', 'RW', 'RWB'], base: 'Midfielder' },
  'federico bernardeschi': { primary: 'RW', positions: ['RW', 'RM', 'CAM'], base: 'Forward' },

  // ==================== FORWARDS: STRIKERS & CENTRE-FORWARDS ====================
  'miroslav klose': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 90 },
  'ruud van nistelrooy': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 92 },
  'thierry henry': { primary: 'ST', positions: ['ST', 'CF', 'LW'], base: 'Forward', baseRating: 93 },
  'robert lewandowski': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 93 },
  'harry kane': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 92 },
  'alan shearer': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 91 },
  'marco van basten': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 94 },
  'gerd muller': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 94 },
  'raul': { primary: 'ST', positions: ['ST', 'CF', 'CAM'], base: 'Forward', baseRating: 91 },
  'david villa': { primary: 'ST', positions: ['ST', 'CF', 'LW'], base: 'Forward', baseRating: 91 },
  'fernando torres': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 90 },
  'wayne rooney': { primary: 'ST', positions: ['ST', 'CF', 'CAM'], base: 'Forward', baseRating: 91 },
  'karim benzema': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 92 },
  'zlatan ibrahimovic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 92 },
  'romelu lukaku': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 89 },
  'alvaro morata': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'andriy shevchenko': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 92 },
  'filippo inzaghi': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 89 },
  'christian vieri': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 90 },
  'jurgen klinsmann': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 90 },
  'rudi voller': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 89 },
  'gary lineker': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 90 },
  'jean-pierre papin': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 90 },
  'patrick kluivert': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 90 },
  'robin van persie': { primary: 'ST', positions: ['ST', 'CF', 'RW'], base: 'Forward', baseRating: 91 },
  'mario balotelli': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'mario mandzukic': { primary: 'ST', positions: ['ST', 'CF', 'LW'], base: 'Forward', baseRating: 88 },
  'olivier giroud': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'ciro immobile': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 88 },
  'davor suker': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 90 },
  'predrag mijatovic': { primary: 'ST', positions: ['ST', 'CF', 'LW'], base: 'Forward', baseRating: 89 },
  'savo milosevic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 88 },
  'hakan sukur': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 89 },
  'henrik larsson': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 89 },
  'pauleta': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 88 },
  'nuno gomes': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'milan baros': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 88 },
  'jan koller': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'tomas necid': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'david lafata': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'tomas pekhart': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'jan rezek': { primary: 'ST', positions: ['ST', 'CF', 'RW'], base: 'Forward' },
  'patrik schick': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 88 },
  'adam hlozek': { primary: 'ST', positions: ['ST', 'LW', 'CF'], base: 'Forward' },
  'jon dahl tomasson': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'ebbe sand': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'nicklas bendtner': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'rasmus hojlund': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 86 },
  'kasper dolberg': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'alexander isak': { primary: 'ST', positions: ['ST', 'CF', 'LW'], base: 'Forward', baseRating: 87 },
  'marcus berg': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'johan elmander': { primary: 'ST', positions: ['ST', 'CF', 'RW'], base: 'Forward' },
  'marcus allback': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'kennet andersson': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'martin dahlin': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'roman pavlyuchenko': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'aleksandr kerzhakov': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'pavel pogrebnyak': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'artem dzyuba': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'semih senturk': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'nihat kahveci': { primary: 'ST', positions: ['ST', 'CF', 'RW'], base: 'Forward', baseRating: 88 },
  'cenk tosun': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'burak yilmaz': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'enes unal': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'baris alper yilmaz': { primary: 'RW', positions: ['RW', 'RM', 'ST', 'LW'], base: 'Forward' },
  'arkadiusz milik': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 86 },
  'krzysztof piatek': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'maciej zurawski': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'emmanuel olisadebe': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'roman yaremchuk': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'artem dovbyk': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'eduardo': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'nikica jelavic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'bruno petkovic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'andrej kramaric': { primary: 'ST', positions: ['ST', 'CF', 'CAM'], base: 'Forward' },
  'christian benteke': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'michy batshuayi': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'lois openda': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'breel embolo': { primary: 'ST', positions: ['ST', 'CF', 'RW'], base: 'Forward' },
  'haris seferovic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'alexander frei': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'marko arnautovic': { primary: 'ST', positions: ['ST', 'CF', 'LW'], base: 'Forward', baseRating: 86 },
  'michael gregoritsch': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'angelos charisteas': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'demis nikolaidis': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'zisis vryzas': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'theofanis gekas': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'dimitris salpingidis': { primary: 'RW', positions: ['RW', 'RM', 'ST'], base: 'Forward' },
  'georgios samaras': { primary: 'LW', positions: ['LW', 'LM', 'ST'], base: 'Forward' },
  'kostas mitroglou': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'robert vittek': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'adam nemec': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'ivan schranz': { primary: 'RW', positions: ['RW', 'RM', 'ST', 'LW'], base: 'Forward' },
  'david strelec': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'aleksandar mitrovic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'dusan vlahovic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward', baseRating: 87 },
  'luka jovic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'darko kovacevic': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },
  'mateja kezman': { primary: 'ST', positions: ['ST', 'CF'], base: 'Forward' },

  // ==================== FORWARDS: WINGERS ====================
  'cristiano ronaldo': { primary: 'LW', positions: ['LW', 'LM', 'ST', 'RW'], base: 'Forward', baseRating: 95 },
  'franck ribery': { primary: 'LW', positions: ['LW', 'CAM', 'LM'], base: 'Forward', baseRating: 92 },
  'eden hazard': { primary: 'LW', positions: ['LW', 'CAM', 'LM'], base: 'Forward', baseRating: 92 },
  'marcus rashford': { primary: 'LW', positions: ['LW', 'LM', 'ST'], base: 'Forward', baseRating: 87 },
  'raheem sterling': { primary: 'LW', positions: ['LW', 'LM', 'RW'], base: 'Forward', baseRating: 88 },
  'jack grealish': { primary: 'LW', positions: ['LW', 'CAM'], base: 'Forward' },
  'rafael leao': { primary: 'LW', positions: ['LW', 'LM', 'ST'], base: 'Forward', baseRating: 88 },
  'nani': { primary: 'LW', positions: ['LW', 'LM', 'RW'], base: 'Forward', baseRating: 87 },
  'ricardo quaresma': { primary: 'RW', positions: ['RW', 'RM', 'LW'], base: 'Forward', baseRating: 87 },
  'pedro': { primary: 'RW', positions: ['RW', 'RM', 'LW'], base: 'Forward', baseRating: 87 },
  'ferran torres': { primary: 'RW', positions: ['RW', 'LW', 'ST'], base: 'Forward', baseRating: 86 },
  'nico williams': { primary: 'LW', positions: ['LW', 'LM', 'RW'], base: 'Forward', baseRating: 88 },
  'anthony martial': { primary: 'LW', positions: ['LW', 'LM', 'ST'], base: 'Forward' },
  'kingsley coman': { primary: 'LW', positions: ['LW', 'LM', 'RW'], base: 'Forward', baseRating: 87 },
  'bradley barcola': { primary: 'LW', positions: ['LW', 'LM', 'RW'], base: 'Forward' },
  'ivan perisic': { primary: 'LW', positions: ['LW', 'LM', 'LB'], base: 'Midfielder', baseRating: 88 },
  'ante rebic': { primary: 'LW', positions: ['LW', 'LM', 'ST'], base: 'Forward' },
  'kerem akturkoglu': { primary: 'LW', positions: ['LW', 'LM'], base: 'Forward' },
  'kenan yildiz': { primary: 'LW', positions: ['LW', 'CAM', 'ST'], base: 'Forward' },
  'mykhailo mudryk': { primary: 'LW', positions: ['LW', 'LM'], base: 'Forward' },
  'viktor tsyhankov': { primary: 'RW', positions: ['RW', 'RM'], base: 'Forward' },
  'kamil grosicki': { primary: 'LW', positions: ['LW', 'LM'], base: 'Midfielder' },
  'przemyslaw frankowski': { primary: 'RM', positions: ['RM', 'RW', 'RWB'], base: 'Midfielder' },
  'denis cheryshev': { primary: 'LW', positions: ['LW', 'LM'], base: 'Midfielder' },
  'yevhen konoplyanka': { primary: 'LW', positions: ['LW', 'LM'], base: 'Forward' },
  'arjen robben': { primary: 'RW', positions: ['RW', 'LW', 'RM'], base: 'Forward', baseRating: 93 },
  'luis figo': { primary: 'RW', positions: ['RW', 'LW', 'CAM'], base: 'Midfielder', baseRating: 92 },
  'gareth bale': { primary: 'RW', positions: ['RW', 'LW', 'ST', 'LB'], base: 'Forward', baseRating: 92 },
  'bukayo saka': { primary: 'RW', positions: ['RW', 'RM', 'LB'], base: 'Forward', baseRating: 89 },
  'lamine yamal': { primary: 'RW', positions: ['RW', 'RM'], base: 'Forward', baseRating: 89 },
  'ousmane dembele': { primary: 'RW', positions: ['RW', 'RM', 'LW'], base: 'Forward', baseRating: 87 },
  'federico chiesa': { primary: 'RW', positions: ['RW', 'LW', 'ST'], base: 'Forward', baseRating: 88 },
  'leroy sane': { primary: 'RW', positions: ['RW', 'RM', 'LW'], base: 'Forward', baseRating: 88 },
  'serge gnabry': { primary: 'RW', positions: ['RW', 'LW', 'ST'], base: 'Forward', baseRating: 87 },
  'dirk kuyt': { primary: 'RW', positions: ['RW', 'ST', 'RB'], base: 'Forward', baseRating: 87 },
  'sylvain wiltord': { primary: 'RW', positions: ['RW', 'RM', 'ST'], base: 'Forward', baseRating: 87 },
  'dejan kulusevski': { primary: 'RW', positions: ['RW', 'CAM', 'RM'], base: 'Forward' },
  'dennis rommedahl': { primary: 'RW', positions: ['RW', 'RM'], base: 'Forward', baseRating: 86 },
  'jesper gronkjaer': { primary: 'LW', positions: ['LW', 'LM', 'RW'], base: 'Forward', baseRating: 86 },
  'mikkel damsgaard': { primary: 'LW', positions: ['LW', 'CAM'], base: 'Forward' },
  'andreas skov olsen': { primary: 'RW', positions: ['RW', 'RM'], base: 'Forward' },
  'andriy yarmolenko': { primary: 'RW', positions: ['RW', 'RM', 'ST'], base: 'Forward', baseRating: 87 },
  'jakub blaszczykowski': { primary: 'RM', positions: ['RM', 'RW'], base: 'Midfielder', baseRating: 86 },
  'cengiz under': { primary: 'RW', positions: ['RW', 'RM'], base: 'Forward', baseRating: 86 },
  'irfan can kahveci': { primary: 'RW', positions: ['RW', 'CAM', 'CM'], base: 'Midfielder' },
  'filip kostic': { primary: 'LM', positions: ['LM', 'LW', 'LWB'], base: 'Midfielder' },
  'dusan tadic': { primary: 'CAM', positions: ['CAM', 'LW', 'RW'], base: 'Midfielder', baseRating: 87 }
}
